### PR TITLE
Removing dead project UberWriter

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @geraldb,

removing a dead project here. I couldn't find the app nor the website anymore.

Cheers!

### CODE REVIEW

**Comment by geraldb** [comment]
Thanks - my google check says:

> UberWriter has been forked into Apostrophe editor.

Maybe change UberWriter to Apostrophe editor (formerly UberWriter) or such, see <https://gitlab.gnome.org/somas/apostrophe>.

**Comment by spekulatius** [comment]
Ah okay. should I replace it with this one?

**Comment by geraldb** [comment]
Yeah if you don't mind would be great to keep the history and just fix the broken link and change the name to something like:    Apostrophe Editor (formerly UberWriter)

**Comment by spekulatius** [comment]
Sure, I can update it.

**Comment by spekulatius** [comment]
How is this @geraldb ?

**Comment by geraldb** [comment]
Looks great. Thanks for taking the time. Keep it up. Cheers. Prost. Greetings from Austria.

**Comment by spekulatius** [comment]
Awesome and no worries! Viele Grüße aus Georgien!

**Pull request merged**
